# Generated by Django 5.1.1 on 2024-09-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Carta', 'Carta'), ('Memorando', 'Memorando'), ('Email', 'Email')], max_length=10)),
                ('entrada_salida', models.CharField(max_length=10)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('consecutivo', models.CharField(max_length=50)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.dependencia')),
            ],
        ),
        migrations.AddField(
            model_name='dependencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
    ]
