# Generated by Django 5.1.1 on 2024-09-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
