# Generated by Django 5.1.1 on 2024-09-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_correspondencia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
            preserve_default=False,
        ),
    ]
