# Generated by Django 5.1.1 on 2024-09-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_gestion_empresa_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=255),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='destinatario',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='remitente',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='respuesta_necesaria',
            field=models.BooleanField(default=False),
        ),
    ]
