# Generated by Django 5.1.1 on 2024-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_correspondencia_asunto_correspondencia_destinatario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondencia',
            old_name='respuesta_necesaria',
            new_name='necesita_respuesta',
        ),
        migrations.RemoveField(
            model_name='correspondencia',
            name='user',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='asunto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='consecutivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='destinatario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='documento',
            field=models.FileField(upload_to='correspondencias/'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='remitente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
