# Generated by Django 5.1.1 on 2024-09-20 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_rename_respuesta_necesaria_correspondencia_necesita_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='correspondencias/'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo',
            field=models.CharField(default='Carta', max_length=50),
        ),
        migrations.CreateModel(
            name='RespuestaCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('correspondencia_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='gestion.correspondencia')),
            ],
        ),
    ]
