# Generated by Django 5.1.1 on 2024-09-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_correspondencia_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestacorrespondencia',
            old_name='texto_respuesta',
            new_name='respuesta',
        ),
        migrations.RemoveField(
            model_name='respuestacorrespondencia',
            name='correspondencia_original',
        ),
        migrations.AddField(
            model_name='respuestacorrespondencia',
            name='correspondencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.correspondencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestacorrespondencia',
            name='fecha_respuesta',
            field=models.DateField(),
        ),
    ]
