# Generated by Django 5.1.1 on 2024-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_empresa_logo_alter_correspondencia_entrada_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='dependencias',
            field=models.ManyToManyField(related_name='usuarios', to='gestion.dependencia'),
        ),
    ]
