# Generated by Django 5.1.1 on 2024-10-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_perfilusuario_dependencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='dependencias',
            field=models.ManyToManyField(blank=True, to='gestion.dependencia'),
        ),
    ]
