# Generated by Django 5.1.1 on 2024-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_perfilusuario_dependencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='empresas',
            field=models.ManyToManyField(blank=True, to='gestion.empresa'),
        ),
    ]
