# Generated by Django 5.1.1 on 2024-10-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_remove_perfilusuario_empresa_perfilusuario_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='documento_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/'),
        ),
        migrations.AddField(
            model_name='respuestacorrespondencia',
            name='documento_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/'),
        ),
    ]
