# Generated by Django 5.1.1 on 2024-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_correspondencia_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_limite_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
