# Generated by Django 5.0.7 on 2024-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_dependencia_inicio_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
